#+TITLE: SPPARKS for microstructural science
#+AUTHOR: Brian DeCost and Liz Holm
#+EMAIL: bdecost@andrew.cmu.edu
#+DATE: 11 July 2014
#+OPTIONS: H:3 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS: TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+startup: beamer
#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [mathserif,xcolor=dvipsnames]
#+BEAMER_FRAME_LEVEL: 2
#+latex_header: \mode<beamer>{\usetheme{Berkeley}}
#+latex_header: \mode<beamer>{\usecolortheme{seahorse}}
#+latex_header: \setbeamertemplate{navigation symbols}{}
#+latex_header: \setbeamertemplate{footline}[frame number]
#+latex_header: \setbeamertemplate{blocks}[rounded] 
#+latex_header: \usepackage{enumitem}
#+latex_header: \setitemize{itemsep=1ex,leftmargin=1cm,labelindent=\parindent,label=$\triangleright$}
#+latex_header: \graphicspath{{images/}}
#+latex_header: \setbeamerfont{title}{family=\rm}
#+latex_header: \setbeamerfont{author}{family=\rm}
#+latex_header: \setbeamerfont{date}{family=\rm}
#+latex_header: \setbeamerfont{frametitle}{family=\rm}
# #+latex_header: \usebackgroundtemplate{\includegraphics[width=\paperwidth]{spkcode-1}}
#+latex_header: \setbeamertemplate{background canvas}{ \begin{picture}(0,0) \put(45,-301){\includegraphics[width=\paperwidth]{spkcode-1}} \end{picture}}
#+BEAMER_HEADER_EXTRA: \title[SPPARKS]{SPPARKS for microstructural science}
#+BEAMER_HEADER_EXTRA: \author[]{Brian DeCost}
#+latex_header: \newcommand{\e}[1]{\textcolor{Periwinkle}{#1}}


* Introduction to =SPPARKS=
\setbeamertemplate{background canvas}[default] 
** \e{S}tochastic \e{P}arallel \e{PAR}ticle \e{K}inetic \e{S}imulator[fn:1]
*** ~SPPARKS~ is an efficient \emph{parallel} Kinetic Monte Carlo framework :B_block:
    :PROPERTIES:
    :BEAMER_env: block
    :END:
    - Mesoscale materials phenomena as stochastic processes
    - Scalable to thousands of processors
    - Modular ~C++~ facilitates user-defined models/statistics
    - Open Source (GPLv3)
    - Related to the ~LAMMPS~ Molecular Dynamics framework

** What applications is ~SPPARKS~ useful for?
   - lattice-based models
   - off-lattice models
   - generic KMC applications
*** In this session, we'll focus on the Potts model		    :B_block:
    :PROPERTIES:
    :BEAMER_env: block
    :END:
- Modeling grain growth, recrystallization, and related phenomena
- Annealing synthetic microstructures to achieve local equilibrium along triple lines
- Generation of simple synthetic microstructures

** Spatially decomposed parallelization

* Getting started with =SPPARKS=
** The =SPPARKS= distribution
Download [[http://www.sandia.gov/~sjplimp/download.html][SPPARKS]] from =http://www.sandia.gov/~sjplimp/download.html=
\bigskip
\begin{block}{Unpack the ~SPPARKS~ source archive}
#+BEGIN_SRC shell
mkdir -p ~/Software && cd ~/Software
tar xvzf ~/Downloads/spparks.tar.gz
cd spparks*/src
ls ~/Software/spparks*/
#+END_SRC
\end{block}
\bigskip

\includegraphics[width=\textwidth]{ls-1}

** =SPPARKS= uses the Unix build system =make=
~SPPARKS~ is distributed with several makefiles, found in ~src/MAKE/~. 

\bigskip
\includegraphics[width=\textwidth]{make-dir-1}
\bigskip

You will likely have to edit ~Makefile.linux~, ~Makefile.g++~, or ~Makefile.mac_mpi~ to reflect your system to get ~SPPARKS~ to compile.[fn:3]

** Building =SPPARKS=

Try to compile =SPPARKS= by running make with the appropriate build target for your system as an argument.

\bigskip
\begin{block}{Building SPPARKS using ~Makefile.mac\_mpi~}
#+BEGIN_SRC shell
make -j4 mac_mpi
#+END_SRC
\end{block}
\bigskip

The result is an executable named ~spk_mac_mpi~ in ~src/~.

** Building serial ~SPPARKS~
The ~JPEG~ library can also cause build problems which are difficult to resolve.
~Makefile.demo~ will build a serial version of ~SPPARKS~ without the ~JPEG~ library.
\begin{block}{First build the ~MPI~ stubs:}
#+BEGIN_SRC shell
cd STUBS
make
cd ..
#+END_SRC
\end{block}

Copy ~Makefile.demo~ into ~src/MAKE/~

\begin{block}{Build the demo version of =SPPARKS=}
#+BEGIN_SRC shell
make demo
#+END_SRC
\end{block}

** "Installing" SPPARKS[fn:2]
\begin{block}
{To avoid copying the ~SPPARKS~ executable or typing the full path to it repeatedly, define a \emph{shell alias}:}
#+BEGIN_SRC shell
alias spk='~/Software/spparks*/src/spk_demo'
#+END_SRC
\end{block}

\bigskip

Now typing ~spk~ into the shell prompt from any working directory runs ~SPPARKS~. Try this now.

** Running ~SPPARKS~ with no input
\begin{block}{~SPPARKS~ reads commands from ~stdin~}
\includegraphics[width=\textwidth]{spk} \\
Press ~Ctrl-C~ to exit.
\end{block}


* Demo: Running =SPPARKS=
** =SPPARKS= input scripts
=SPPARKS= is controlled by a script of commands which are executed line-by-line.

\bigskip

\begin{block}{Run the =basic= demo}
#+BEGIN_SRC shell
cd ~/Downloads/spparks-demo-master/demos/basic
spk < basic.spkin
#+END_SRC
\end{block}

** Anatomy of an  input script: =basic.spkin=
#+BEGIN_SRC shell
# Minimal SPPARKS Potts script
seed             56789
app_style        potts 100
dimension        3
lattice          sc/26n 1.0
region           box block 0 32 0 32 0 32
create_box       box
create_sites     box
set              site range 1 100
solve_style      tree
diag_style       energy
stats            10.0
run              100.0
#+END_SRC

* Demo: Grain growth kinetics
** Diagnostics
** Log file
* Demo: Visualization with ParaView
** The =dump= command
Post-processing. =pizza.py= or custom scripts.
** Installing pizza.py[fn:4]
Download and unpack the [[http://www.sandia.gov/~sjplimp/download.html][pizza.py]] archive from =http://www.sandia.gov/~sjplimp/download.html=
\bigskip
\begin{block}{Unpack the ~SPPARKS~ source archive}
#+BEGIN_SRC shell
mkdir -p ~/Software && cd ~/Software
tar xvzf ~/Downloads/pizza.tar.gz
cd -
alias pizza='python -i ~/Software/pizza*/src/pizza.py'
#+END_SRC
\end{block}
\bigskip

** Conversion to =vtk= with =pizza.py=

* Running =SPPARKS= in parallel
** =mpirun=
** Processor partitions

* Footnotes

[fn:1] [[http://spparks.sandia.gov/]]

[fn:2] To make this persistent, append this command to =~/.bashrc= (=~/.bash_profile= on a mac)

[fn:3] You'll likely need to supply the location of the =MPI= library files on your system.

[fn:4] As with =SPPARKS=, append the =alias= command to =~/.bashrc= or =~/.bash_profile= to make this "installation" persistent.

